FROM python:3.10

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install gunicorn==20.1.0

RUN pip install -r requirements.txt --no-cache-dir

COPY . .


CMD ["gunicorn", "--bind", "0.0.0.0:9000", "kittygram_backend.wsgi"]